singularity_freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
singularity_connectome_workbench: /project/6007967/software/transparentsingularity/connectome-workbench_1.4.1_20191117.simg/connectome-workbench_1.4.1_20191117.simg 

#path to your freesurfer license file:
fs_license: /project/6050199/akhanf/opt/freesurfer/.license

#path to subject freesurfer dir (containing surf/ and mri/ subfolders) 
# use the {subject} wildcard here.. 
in_freesurfer: /scratch/akhanf/hcp1200_freesurfer/{subject}

participants_tsv: config/participants.tsv
