
participants_tsv: 'config/participants.tsv'


#singularity containers:
singularity:
  neuroglia: docker://khanlab/neuroglia-core:latest
  freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
  connectome_workbench: /project/6007967/software/transparentsingularity/connectome-workbench_1.4.1_20191117.simg/connectome-workbench_1.4.1_20191117.simg 

#path to your freesurfer license file:
fs_license: /project/6050199/akhanf/opt/freesurfer/.license



#set-up paths to inputs here:


#path to subject freesurfer dir (containing surf/ and mri/ subfolders) 
# use the {subject} wildcard here.. 

in_freesurfer: /scratch/akhanf/hcp1200_freesurfer/{subject}



template_prob_seg: 
  rpiriform: '/scratch/nchris5/HCP_template_piriform_segmentations/Full_Right_BigBrain_to_HCPSubject_Space_Registration_SmoothedDownsampled/Right_piriform_segmentation_BigBrain_to_HCPtemplate_labeltolabelReg/BigBrainSeg_in_HCPtemplateSegSpace07mm_Smoothed07FWHM_Downsampled.nii.gz'

#to apply to masks in target space before tracking, and template-space before grouping..
prob_seg_threshold: 0.5


template: hcp7Tsubj
ants_affine_mat: /project/6050199/ext-data/hcp1200/deriv/ants_build_template_hcp_7Tsubj_07mm/results/iter_1/sub-{subject}_0GenericAffine.mat
ants_invwarp_nii: /project/6050199/ext-data/hcp1200/deriv/ants_build_template_hcp_7Tsubj_07mm/results/iter_1/sub-{subject}_1InverseWarp.nii.gz
ants_warp_nii: /project/6050199/ext-data/hcp1200/deriv/ants_build_template_hcp_7Tsubj_07mm/results/iter_1/sub-{subject}_1Warp.nii.gz
ants_ref_nii: /project/6050199/ext-data/hcp1200/deriv/ants_build_template_hcp_7Tsubj_07mm/results/iter_1/template_T1w.nii.gz

#list of ROIs in target segmentations 
targets_dseg_tsv: resources/label-hcpmmp180_dseg.tsv
targets_atlas_name: hcpmmp180 #must be [a-zA-Z0-9]+

#bedpost
fsl_bedpost_dir: /project/6007967/akhanf/projects/hcp/HCP_1200_T1w_Diffusion_FS
bedpost_mean_s0_samples: '{subject}/T1w/Diffusion.bedpostX/mean_S0samples.nii.gz'
bedpost_merged_prefix: '{subject}/T1w/Diffusion.bedpostX/merged'

#maximum number of clusters in spectral clustering
# will perform with k=range(2,max_k+1)
max_k: 4


#tractography parameters
probtrack:
    seed_resolution: 1.0
    res_name: dwi # bids deriv filename will have res-{res_name}

    nsamples: 10000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 


probtrack_tractmap:
    seed_resolution: 0.5
    res_name: super #bids deriv filename will have res-{res_name}
    nsamples: 1000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --randfib=2' 






